language: node_js
node_js:
- '10.14'

dist: trusty
sudo: false

branches:
  only:
  - master

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
  - node_modules

install:
- npm install -g yarn

script:
- yarn lint
- ng test --watch=false --progress=false --browsers=ChromeHeadlessCI
- yarn build --base-href https://sobolevsky.anton.github.io/angular-project/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/angular-project
  on:
    branch: master
